name: shop_wise
description: "Aplicativo para controlar compras diárias."
publish_to: 'none' 
version: 1.3.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  sqflite: ^2.3.3+1
  flutter_launcher_icons: ^0.14.4
  share_plus: ^12.0.1
  path_provider: ^2.1.2
  file_picker: ^10.3.7
  permission_handler: ^12.0.1
  lottie: ^3.1.2
  uri_to_file:
    path: ../uri_to_file
  replace_diacritic:
    git:
      url: https://github.com/victorfidelis/replace_diacritic.git
      ref: main 
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  sqflite_common_ffi:
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_shop_wise_08.png"
  min_sdk_android: 21 